### ISSUE TITLE
【レビュー依頼】DB設計

### ISSUE THREAD

**Issue by DAIHI** [we-b/PHP_Pictweet#2]
## 実装機能及びその順序
※実装の詳細は担当者が逐次考え相談する

#### 1. ユーザー機能
- サインアップ
- ログイン
- マイページ

### tweets
- ツイート情報

| Field | Type | Null | Key | Default | Extra |
| :------: |:---:| :--------: | :------: | :-----:| :-----:|
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| text       | text             | NO   |     | NULL    |                |
| image      | text             | NO   |     | NULL    |                |
| created_at | timestamp        | YES  |     | NULL    |                |
| updated_at | timestamp        | YES  |     | NULL    |                |
| user_id    | int(11)          | NO   | MUL | NULL    | foreign_key: true |

画像(image)はURIを取得し保存する

- Association
  - belongsTo: user
  - hasMany: comments

### comments
- コメント情報

| Field      | Type             | Null | Key | Default | Extra          |
| :------: |:---:| :--------: | :------: | :-----:| :-----:|
| id         | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| user_id    | int(11)          | NO   | MUL | NULL    | foreign_key: true |
| tweet_id   | int(11)          | NO   | MUL | NULL    | foreign_key: true |
| text       | text             | NO   |     | NULL    |                |
| created_at | timestamp        | YES  |     | NULL    |                |
| updated_at | timestamp        | YES  |     | NULL    |                |

- Association
  - belongsTo: user
  - belongsTo: tweet

### users
- ユーザー情報

| Field      | Type             | Null | Key | Default | Extra          |
| :------: |:---:| :--------: | :------: | :-----:| :-----:|
| id             | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| name           | varchar(255)     | NO   |     | NULL    |                |
| email          | varchar(255)     | NO   | UNI | NULL    |                |
| password       | varchar(255)     | NO   |     | NULL    |                |
| remember_token | varchar(100)     | YES  |     | NULL    |                |
| created_at     | timestamp        | YES  |     | NULL    |                |
| updated_at     | timestamp        | YES  |     | NULL    |                |

- Association
  - hasMany: tweets
  - hasMany: comments

**Comment by rokuyamad** [comment]
commentsテーブルですが、`user_id`と`tweet_id`がforeign keyであること追記したほうがいいと思います！
後は問題ありません！
